### ISSUE TITLE
[Bug] Scraping issues

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#107]
**RomM version**
docker:latest(1.6)

**Describe the bug**
Some games are scraped wrongly, in my case:
- "Medabots AX" was scraped as "Medabots" (GBA)
- "Medabots AX" was not scrpaed/not found (GBA)

**To Reproduce**
1. Add both "Medabots AX" and "Medabots" games on your GBA folder (both Rokusho and Metabee version got the issue)
2. Scrape them

**Expected behavior**
They are scraped correctly

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/6771419/229459341-e45b08ce-4d6c-46ec-ac66-6648dc6a773e.png)

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS (Linux Debian)
 - Browser Vivaldi, Chrome
 - Version latest on 29/03/2023

**Comment by zurdi15** [comment]
Hi! I think I am not understanding well the issue as I didn't know this games saga. In this part, those are different games?:
 
>     * "Medabots AX" was scraped as "Medabots" (GBA)
> 
>     * "Medabots AX" was not scrpaed/not found (GBA)

In my tests, my folder were like this:
![imagen](https://user-images.githubusercontent.com/34356590/229774933-1c24485c-9ab9-4c7e-854d-4915fb74773a.png)
![imagen](https://user-images.githubusercontent.com/34356590/229776420-d1a39f2d-23dd-4833-8c21-2aa2a50149e6.png)


After using the ``search IGDB`` feature could parse all of them without problems (and in my case renaming the files with the ``rename as IGDB`` feature) this is how it looks like:

![imagen](https://user-images.githubusercontent.com/34356590/229775892-35efb8e5-533e-486e-ab39-0d52752548f4.png)
![imagen](https://user-images.githubusercontent.com/34356590/229775936-5a9913b5-2a9d-4178-b413-78ea0e07688e.png)

keep in mind that the quality of the automatic scan depends on IGDB search engine.

**Comment by XargonWan** [comment]
Sorry to write here again but I found a bug in the Switch system.
The DLC folder is recognized as "UNO" for some reason, and Live a Live is recognized as Mario Kart, the filename is Live A `Live [0100CF801776C000][v0].nsp` and if you search the code Live a Live is correct.

![image](https://user-images.githubusercontent.com/6771419/231689742-9ca7ca00-757c-4312-a54c-6239939ed74c.png)

**Comment by zurdi15** [comment]
Hey dude no problem.

RomM has nothing to do with failed autoscan games. If one game is not properly identified is because how the IGDB serach engine works. This can be fixed in two ways:

 -  Let the ``Search IGDB`` button show you all the coincidences and choose which one you want:
 
![imagen](https://user-images.githubusercontent.com/34356590/231695834-42c0c4a8-379b-43a2-a253-d35320619197.png)

 - Now you can search directly in IGDB by id if the search engine doesn't find what you want (you need first to go to IGDB, find your game and copy the game ID): 
 
![imagen](https://user-images.githubusercontent.com/34356590/231696198-2d0bb33c-8818-4836-a93b-507669b6e15b.png)

**Comment by XargonWan** [comment]
Yes, that's its what I did in the end.
Thanks.
