### ISSUE TITLE
Unable to pull artwork from IGDB

### ISSUE THREAD

**Issue by nintendogamer15** [zurdi15/romm#17]
So I've followed the example docker compose and deployed it with my Client ID/Secret but for some reason when I try to pull the artwork for a game, it says no results found. Here are my logs from startup to when I get that error:

![image](https://user-images.githubusercontent.com/23743194/228097088-024f8c78-8ac1-4797-b7c0-619201ca2d34.png)

I'm running the docker container on a server running OMV, and deployed the compose through Portainer if that helps.

**Comment by zurdi15** [comment]
Okay I can see the problem now. Your gba folder is uppercase, and I didn't implement the logic for non-case-sensitive platforms names, so it doesn't find the platform id and gets that error. Try to rename your GBA folder to gba.

In any case, I will implement a non-case-sensitive rule for that, is so solly that it fails because of that.

Let me know if it works, and if it works we can close the issue!

**Comment by nintendogamer15** [comment]
> Your gba folder is uppercase, and I didn't implement the logic for non-case-sensitive platforms names, so it doesn't find the platform id and gets that error. Try to rename your GBA folder to gba.
> 
> In any case, I will implement a non-case-sensitive rule for that, it's so silly that it fails because of that.
> 
> Let me know if it works, and if it works we can close the issue!

Oh wow, that was it! I can't believe I didn't think about case sensitivity.
