### ISSUE TITLE
[Other] Do I need to backup the `resources` directory?

### ISSUE THREAD

**Issue by ThibaultNocchi** [zurdi15/romm#355]
Hello, thank your for your software first! :)

I'm setting up backup of the data of Romm on my hosts. I was wondering if the `resources` directory and its images are needed in a backup, or are they recreated/refetched if needed?

Thank you!

**Comment by zurdi15** [comment]
Hi! Thank you first of all.

If you are backing up the database and don't backup the `resources` direectory, you will need to perform a `complete rescan` in order to tell RomM that fetch resources again is needed. I recommend you to backup the `resources` folder to avoid rescans, but its up to you :)

**Comment by GAntoine** [comment]
Like zurdi mentione how easy or hard it is to rebuild the resources directory is definitely a concern. In RomM's case it more or less comes down to the size of your library and waiting the length of a full rescan.

There's also the consideration of file size; if you have 300MB of 8-bit games, you resources folder will faaaarr outsize it. Likewise a single Switch game will take more space then all your resources combined.

**Comment by ThibaultNocchi** [comment]
Thanks for your answers. Effectively I didn't look at that with the right angle: I was looking to backup only the Romm data, and not the roms themselves. If I bundle them up, resources won't take that much size.

Thanks for the clarifications!
