### ISSUE TITLE
[Feature] Remove or hide platform with 0 content

### ISSUE THREAD

**Issue by Djiit** [zurdi15/romm#396]
**Is your feature request related to a problem? Please describe.**

It would be nice to be able to delete a platform from the UI, or at least hide it when there is no content.
Scenario: a first scan scanned a single txt file on a given platform, so I updated my config file to exclude txt files,  but now the platform is just "empty".

**Describe the solution you'd like**

Either auto hide/remove empty platforms.

**Describe alternatives you've considered**

- edit the db by hand? not very handy :/
- exclude them in the config? (I'm planning to add roms, I just don't have yet).

**Additional context**

![image](https://github.com/zurdi15/romm/assets/1169844/932c7301-bec8-408e-8347-8fa39306f88f)

(edit: added a screenshot :D )

**Comment by zurdi15** [comment]
Issue closed in #414

**Comment by MMagTech** [comment]
Ran into this from the other side, I maintain Cabinet, a third-party iOS/tvOS client for RomM (https://github.com/MMagTech/cabinet). Had a couple of platforms end up empty after I deleted the ROMs, and they kept showing up in Cabinet with 0 games since the API still returns them.

First thing I assumed was it was my app's bug. Went looking in the RomM web UI to clean them up and couldn't find them anywhere, not in Platforms, not in admin. Ended up deleting them straight through `DELETE /api/platforms/{id}`.

Seems like #414 hid empty platforms from the browsing views but didn't give a way to actually manage or delete them, so they're invisible rather than gone. Would be nice to have somewhere to find and clear these out (even just Library Management filterable to 0-count), or auto-prune when the last ROM is removed.
