### ISSUE TITLE
[Other] Alternative metadata sources

### ISSUE THREAD

**Issue by pbuyle** [zurdi15/romm#47]
If you are add more sources for game metadata:

- https://thegamesdb.net
- https://www.screenscraper.fr
- http://adb.arcadeitalia.net

**Comment by crispybegs** [comment]
this morning I was trying to match a rom called 'Yoshi's Universal Gravitation' which is the european name for something that's called 'Yoshi Topsy-Turvy' in the US.

RomM was giving a 'no results found' message whgen it searched IGDB, and I'm guessing that's because IGDB either exclusively or in many cases only sees the US as the standard, which is what we see when searching manually:

<img width="549" alt="Screenshot 2023-03-29 at 11 16 23" src="https://user-images.githubusercontent.com/129169122/228503436-3486f4bd-87e2-4687-8f48-8861dabf5afd.png">

Once I changed the filename to 'Yoshi Topsy-Turvy' RomM immediately found the match and completed the metadata.

In complete reverse, screenscraper.fr finds 'Yoshi's Universal Gravitation' but doesn't find 'Yoshi Topsy-Turvy'

<img width="1332" alt="Screenshot 2023-03-29 at 11 17 41" src="https://user-images.githubusercontent.com/129169122/228504065-068601ef-6ed2-4b31-8557-0a80ad445d30.png">

<img width="1265" alt="Screenshot 2023-03-29 at 11 18 31" src="https://user-images.githubusercontent.com/129169122/228504093-9733cc28-21ef-43e3-b4a8-bab8459f3f39.png">

I wonder if there actually exists a source that can handle multi-region releases / naming because there'll be a lot of manual matching like this that needs doing if there isn't.

**Comment by zurdi15** [comment]
This can be solved with IGDB itself, but needs an extra feature implementation that searchs every alternative name of one game. If you look at the IGDB API or the web page, you can see this section:

![imagen](https://user-images.githubusercontent.com/34356590/228509661-4bae0e51-1ecc-40bb-9dde-09e6005373b1.png)

This will be implemented in the near future. Just open the issue for it [#75](https://github.com/zurdi15/romm/issues/75)

**Comment by crispybegs** [comment]
ah nice, i couldn't find it on IGDB via a normal manual search

**Comment by zurdi15** [comment]
Yeah my guess is that the IGDB web search only searches for main title but not alternatives

**Comment by zurdi15** [comment]
I am closing this because I have no plans for support more metadata sources for the moment.

**Comment by nomandera** [comment]
https://github.com/rommapp/romm/issues/821#issuecomment-2131932760

Cross linking as landing here seems a conclusive no when it seems that may not necessarily still be the case.

**Comment by dd900** [comment]
thegamesdb.net now has a new API request system and it is really easy to get a key. They respond really fast too. Aside from the API you can download their entire database in JSON format (https://cdn.thegamesdb.net/json/database-latest.json). The only downside to the json file is that Genres, Publishers, Developers, etc. are all listed as lists of integers. You have to make a few API calls to get the rest of the data and their corresponding IDs.

https://api.thegamesdb.net/v1/Genres?apikey=
https://api.thegamesdb.net/v1/Developers?apikey=
https://api.thegamesdb.net/v1/Publishers?apikey=
https://api.thegamesdb.net/v1/Countries?apikey=
https://api.thegamesdb.net/v1/Regions?apikey=

These files don't need to be updated very often as the data doesn't change often
