### ISSUE TITLE
Scanning, What Next?

### ISSUE THREAD

**Issue by gantoine** [zurdi15/romm#594]
<sup>Originally posted by **Budlyte** January  9, 2024</sup>

What do I do once I'm at this point? 
![image](https://github.com/zurdi15/romm/assets/4451365/19401e5a-0d47-4cf2-9af3-918cb4f87c81)

My Platforms library doesn't update and I can't find anything to click to do anything else.

I am running in Unraid, so maybe there's an issue with my database connection?

**Comment by gantoine** [comment]
Your scan found platforms but likely no games, can you open the logs and paste them here? There should be lines like `0 roms found for platform x`.

**Comment by Budlyte** [comment]
Yeah, here's some examples.
My library is the ROMS folder. I didn't like giving Romms access to the parent folder because other things are there as well.

INFO:     [RomM][2024-01-09 15:42:20] · SNES
INFO:     [RomM][2024-01-09 15:42:20]   Identified as Super Nintendo Entertainment System 🎮
ERROR:    [RomM][2024-01-09 15:42:20] Roms not found for platform SNES. Check RomM folder structure here: https://github.com/zurdi15/romm#-folder-structure
![image](https://github.com/zurdi15/romm/assets/4451365/ea1e190f-0307-4feb-a224-60616bbee2fe)

INFO:     [RomM][2024-01-09 15:42:19] Found 13 platforms in file system 
INFO:     [RomM][2024-01-09 15:42:19] · N64
INFO:     [RomM][2024-01-09 15:42:20]   Identified as Nintendo 64 🎮
ERROR:    [RomM][2024-01-09 15:42:20] Roms not found for platform N64. Check RomM folder structure here: https://github.com/zurdi15/romm#-folder-structure
![image](https://github.com/zurdi15/romm/assets/4451365/944c75d8-97a7-418b-8f1a-5c1083e5442f)

**Comment by gantoine** [comment]
can you post your docker compose, or the section where you mount the folder/folders into romm?

**Comment by Budlyte** [comment]
![image](https://github.com/zurdi15/romm/assets/4451365/27d3c1f2-1443-425f-9628-f2a512589508)

**Comment by Budlyte** [comment]
![image](https://github.com/zurdi15/romm/assets/4451365/eb780a7f-f987-4d6a-94e4-fc3dc2441251)

**Comment by gantoine** [comment]
Change your mount to either of these 2 options: 
- `/mnt/user/Games:/romm/library` and use this env variable: `ROMS_FOLDER_NAME=ROMS`
- `/mnt/user/Games/ROMS:/romm/library/roms`

**Comment by Budlyte** [comment]
It's straight forward in Unraid, click edit and you get this kinda popup.
![image](https://github.com/zurdi15/romm/assets/4451365/5266a388-70a8-48c0-9519-8894d44e7a24)


That did it! Scanning games now. Thank you.
![image](https://github.com/zurdi15/romm/assets/4451365/85f55f3c-f80f-4c6f-97d4-f0cceb7b48c3)

From the Readme, I got that it would detect the folder structure and scan in that manner.
https://github.com/zurdi15/romm?tab=readme-ov-file#%EF%B8%8F-configuration-file

**Comment by gantoine** [comment]
Awesome! Romm expects you to mount a folder with another folder called `roms` in it, which happens in both cases above. That being said there are some improvements we can make to our docs.
