### ISSUE TITLE
[Feature] Support "Alternate titles" from IGDB

### ISSUE THREAD

**Issue by Kelduum** [zurdi15/romm#637]
At the moment, scanning a moderately large from set works okay, but if a game has an alternate title in another region (eg: 'Cybernator' vs 'Assault Suits Valken', 'Resident Evil' vs 'Biohazard', 'Wipeout 2047' vs 'Wipeout XL') it's not picked up in automatic or manual searches, so involves digging around in IMGB for the ID number so you can match it that way.

Ideally, it should also search for matching Alternate/Localised/Romanised names if there's not a direct match.

An alternative is to bundle up similar versions of a game into one directory, but that's not ideal when the game already comes on multiple discs, and that just leads to more issues when you go looking for something, meaning you have to stick with the IGDB naming preferences.

**Comment by Casuallynoted** [comment]
Hello! We do track this in an issue here: #75 , I totally agree this would majorly help with identifying roms! Atm they're looking at options to add additional metadata providers too, like Screenscraper, so that should help with both platform coverage and differential game titles. Ideally, we'll wind up having both :)

Also somewhat unrelated but IGDB sticks with some REALLY weird main titles for games sometimes haha

**Comment by gantoine** [comment]
Closing this in favor of #75, thx for pointing that out noted
