### ISSUE TITLE
[Feature] Scan a new platform alone instead of scan the whole library

### ISSUE THREAD

**Issue by zurdi15** [zurdi15/romm#90]
**Is your feature request related to a problem? Please describe.**
When adding a new platform there is no option to just scan the new one.

**Comment by nintendogamer15** [comment]
This would be great because for some reason after adding two console collections, when I try to scan another one in it scans my already there library, and hits some kind of timeout error by the time it gets to anything that actually needs scanned.
Logs: 
![image](https://user-images.githubusercontent.com/23743194/229105274-022d9e37-9d60-433b-a62f-6484720fff70.png)

**Comment by zurdi15** [comment]
Added in [v1.6](https://github.com/zurdi15/romm/releases/tag/v1.6)
